use crate::core::{placement::types::PlacementError, UNKNOWN_MODEL_ID};
use axum::{
    http::{HeaderMap, HeaderValue, StatusCode},
    response::{IntoResponse, Response},
    Json,
};
use serde::Serialize;

#[derive(Serialize)]
pub struct ErrorResponse<'a> {
    error: ErrorDetail<'a>,
}

#[derive(Serialize)]
struct ErrorDetail<'a> {
    #[serde(rename = "type")]
    error_type: &'static str,
    code: &'a str,
    message: &'a str,
}

pub fn payload<'a>(status: StatusCode, code: &'a str, message: &'a str) -> ErrorResponse<'a> {
    ErrorResponse {
        error: ErrorDetail {
            error_type: status_code_to_str(status),
            code,
            message,
        },
    }
}

#[derive(Clone)]
pub struct MeshLocalError {
    code: String,
    message: String,
}

impl MeshLocalError {
    /// API-specific envelope for errors generated by mesh itself.
    pub fn payload(path: &str, status: StatusCode, code: &str, message: &str) -> serde_json::Value {
        let messages = path.split('?').next() == Some("/v1/messages");
        let kind = match status.as_u16() {
            413 if messages => "request_too_large",
            529 if messages => "overloaded_error",
            401 => "authentication_error",
            403 => "permission_error",
            404 => "not_found_error",
            429 => "rate_limit_error",
            400..=499 => "invalid_request_error",
            _ => "api_error",
        };
        if messages {
            serde_json::json!({"type": "error", "error": {"type": kind, "message": message}})
        } else {
            serde_json::json!({"error": {"type": kind, "code": code, "message": message}})
        }
    }

    pub fn response(path: &str, status: StatusCode, code: &str, message: &str) -> Response {
        Self::format_response(path, create_error(status, code, message))
    }

    pub fn format_response(path: &str, mut response: Response) -> Response {
        let Some(error) = response.extensions().get::<Self>() else {
            return response;
        };
        let body = serde_json::to_vec(&Self::payload(
            path,
            response.status(),
            &error.code,
            &error.message,
        ))
        .expect("error payload is serializable");
        response.headers_mut().remove(http::header::CONTENT_LENGTH);
        response.headers_mut().insert(
            http::header::CONTENT_TYPE,
            HeaderValue::from_static("application/json"),
        );
        if response.status() == StatusCode::METHOD_NOT_ALLOWED {
            response
                .headers_mut()
                .insert(http::header::ALLOW, HeaderValue::from_static("POST"));
        }
        *response.body_mut() = axum::body::Body::from(body);
        response
    }
}

pub const HEADER_X_MESH_ERROR_CODE: &str = "X-Mesh-Error-Code";

pub fn internal_error(code: impl Into<String>, message: impl Into<String>) -> Response {
    create_error(StatusCode::INTERNAL_SERVER_ERROR, code, message)
}

pub fn bad_request(code: impl Into<String>, message: impl Into<String>) -> Response {
    create_error(StatusCode::BAD_REQUEST, code, message)
}

pub fn not_found(code: impl Into<String>, message: impl Into<String>) -> Response {
    create_error(StatusCode::NOT_FOUND, code, message)
}

pub fn service_unavailable(code: impl Into<String>, message: impl Into<String>) -> Response {
    create_error(StatusCode::SERVICE_UNAVAILABLE, code, message)
}

pub fn failed_dependency(code: impl Into<String>, message: impl Into<String>) -> Response {
    create_error(StatusCode::FAILED_DEPENDENCY, code, message)
}

pub fn not_implemented(code: impl Into<String>, message: impl Into<String>) -> Response {
    create_error(StatusCode::NOT_IMPLEMENTED, code, message)
}

pub fn bad_gateway(code: impl Into<String>, message: impl Into<String>) -> Response {
    create_error(StatusCode::BAD_GATEWAY, code, message)
}

pub fn method_not_allowed(code: impl Into<String>, message: impl Into<String>) -> Response {
    create_error(StatusCode::METHOD_NOT_ALLOWED, code, message)
}

pub fn create_error(
    status: StatusCode,
    code: impl Into<String>,
    message: impl Into<String>,
) -> Response {
    let code_str = code.into();
    let message_str = message.into();

    let mut headers = HeaderMap::with_capacity(1);
    headers.insert(
        HEADER_X_MESH_ERROR_CODE,
        HeaderValue::from_str(&code_str).unwrap(),
    );

    let mut response = (
        status,
        headers,
        Json(payload(status, &code_str, &message_str)),
    )
        .into_response();
    response.extensions_mut().insert(MeshLocalError {
        code: code_str,
        message: message_str,
    });
    response
}

fn status_code_to_str(status_code: StatusCode) -> &'static str {
    status_code
        .canonical_reason()
        .unwrap_or("Unknown Status Code")
}

pub fn extract_error_code_from_response<B>(response: &Response<B>) -> &str {
    response
        .headers()
        .get(HEADER_X_MESH_ERROR_CODE)
        .and_then(|v| v.to_str().ok())
        .unwrap_or_default()
}

#[derive(Debug, thiserror::Error)]
#[error("{message}")]
pub struct IngressError {
    pub status: StatusCode,
    pub code: &'static str,
    pub message: String,
}
impl From<crate::core::prepare_pool::PrepareError> for IngressError {
    fn from(error: crate::core::prepare_pool::PrepareError) -> Self {
        Self::new(
            StatusCode::from_u16(error.status_code()).expect("valid prepare error status"),
            error.code(),
            error.to_string(),
        )
    }
}

impl IngressError {
    pub fn new(status: StatusCode, code: &'static str, message: impl Into<String>) -> Self {
        Self {
            status,
            code,
            message: message.into(),
        }
    }
    pub fn invalid(message: impl Into<String>) -> Self {
        Self::new(StatusCode::BAD_REQUEST, "invalid_request", message)
    }
    pub fn response(&self, path: &str) -> Response {
        MeshLocalError::response(path, self.status, self.code, &self.message)
    }

    pub fn placement(err: PlacementError, model_id: Option<&str>) -> Self {
        let model = model_id.unwrap_or(UNKNOWN_MODEL_ID);
        let (code, message) = match &err {
            PlacementError::NoWorkers => (
                "no_workers",
                format!("No workers in registry (model: {})", model),
            ),
            PlacementError::NoAvailableWorkers => (
                "no_available_workers",
                format!("No available workers for model: {}", model),
            ),
            PlacementError::NoPrefillWorkers => (
                "no_prefill_workers",
                format!("No available prefill workers for model: {}", model),
            ),
            PlacementError::NoDecodeWorkers => (
                "no_decode_workers",
                format!("No available decode workers for model: {}", model),
            ),
            PlacementError::PolicyReturnedNone => (
                "policy_returned_none",
                format!(
                    "Load balancing policy returned no worker for model: {}",
                    model
                ),
            ),
            PlacementError::ModelNotFound { model_id } => {
                ("model_not_found", format!("Model not found: {}", model_id))
            }
        };
        Self::new(StatusCode::SERVICE_UNAVAILABLE, code, message)
    }
}
